### ISSUE TITLE
2.0.0版本的crontab启动时报错

### ISSUE THREAD

**Issue by tyhcmzy** [hyperf/crontab#2]
![微信图片_20200624135520](https://user-images.githubusercontent.com/31151479/85506166-6ce03e00-b622-11ea-8f4c-11b4a8e7ccc6.png)

![微信图片_20200624135459](https://user-images.githubusercontent.com/31151479/85506182-723d8880-b622-11ea-953d-a90694911408.png)
![微信图片_20200624135514](https://user-images.githubusercontent.com/31151479/85506191-749fe280-b622-11ea-9d37-fc2124e7b58b.png)

如上图，1.1.26版本是正常的，2.0.0版本报错

**Comment by tyhcmzy** [comment]
![aa](https://user-images.githubusercontent.com/31151479/85506930-f2182280-b623-11ea-813e-56d15b866230.png)
上图中，2.0.0的图片发错了

**Comment by actoy** [comment]
同样的问题

**Comment by huangzhhui** [comment]
请先根据 2.0 升级指南的步骤进行升级处理
