### ISSUE TITLE
2.0.0版本安装好像不兼容

### ISSUE THREAD

**Issue by ArcherZdip** [hyperf/crontab#3]
Fatal error: Declaration of Hyperf\Crontab\Process\CrontabDispatcherProcess::isEnable($server): bool must be compatible with Hyperf\Process\AbstractProcess::isEnable(): bool in /hyperf/vendor/hyperf/crontab/src/Process/CrontabDispatcherProcess.php on line 23

**Comment by limingxinleo** [comment]
composer info | grep hyperf

**Comment by ArcherZdip** [comment]
2.0.0 就有这个问题， 我换成1.1.26就好了。

完整composer info
hyperf/cache                         v1.1.22  A cache component for hyperf.
hyperf/command                       v1.1.21  Command for hyperf
hyperf/config                        v1.1.22  An independent component that provides configuration container.
hyperf/constants                     v1.1.22  A constants component for hyperf.
hyperf/contract                      v1.1.22  The contracts of Hyperf.
hyperf/crontab                       v1.1.26  A crontab component for Hyperf.
hyperf/database                      v1.1.22  A flexible database library.
hyperf/db-connection                 v1.1.22  A hyperf db connection handler for hyperf/database.
hyperf/devtool                       v1.1.22  A Devtool for Hyperf.
hyperf/di                            v1.1.22  A DI for Hyperf.
hyperf/dispatcher                    v1.1.22  A HTTP Server for Hyperf.
hyperf/event                         v1.1.22  an event manager that implements PSR-14.
hyperf/exception-handler             v1.1.6   Exception handler for hyperf
hyperf/framework                     v1.1.22  A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microservices and middlewares.
hyperf/guzzle                        v1.1.23  Swoole coroutine handler for guzzle
hyperf/http-message                  v1.1.22  microservice framework base on swoole
hyperf/http-server                   v1.1.22  A HTTP Server for Hyperf.
hyperf/json-rpc                      v1.1.30  A JSON RPC component for Hyperf RPC Server or Client.
hyperf/load-balancer                 v1.1.22  A load balancer library for Hyperf.
hyperf/logger                        v1.1.22  A logger component for hyperf.
hyperf/memory                        v1.1.22  An independent component that use to operate and manage memory.
hyperf/model-cache                   v1.1.22  A model cache component for hyperf.
hyperf/model-listener                v1.1.22  A model listener for Hyperf.
hyperf/paginator                     v1.1.22  A paginator component for hyperf.
hyperf/pool                          v1.1.23  An independent universal connection pool component.
hyperf/process                       v1.1.22  A process component for hyperf.
hyperf/redis                         v1.1.22  A redis component for hyperf.
hyperf/rpc                           v1.1.22  A rpc basic library for Hyperf.
hyperf/rpc-client                    v1.1.23  An abstract rpc server component for Hyperf.
hyperf/rpc-server                    v1.1.26  An abstract rpc server component for Hyperf.
hyperf/server                        v1.1.22  A base server library for Hyperf.
hyperf/snowflake                     v1.1.22  A snowflake library
hyperf/testing                       v1.1.23  Testing for hyperf
hyperf/translation                   v1.1.17  An independent translation component, forked by illuminate/translation.
hyperf/utils                         v1.1.22  A tools package that could help developer solved the problem quickly.
hyperf/validation                    v1.1.22  hyperf validation

**Comment by limingxinleo** [comment]
贴一下你换成2.0的composer info

**Comment by aji88** [comment]
我这里也是这种情况：

96qbhy/hyperf-auth                   v1.6.1      hyperf 的 auth 组件
hyperf/amqp                          v1.1.32     A amqplib for hyperf.
hyperf/async-queue                   v1.1.26     A async queue component for hyperf.
hyperf/cache                         v1.1.30     A cache component for hyperf.
hyperf/command                       v1.1.32     Command for hyperf
hyperf/config                        v1.1.26     An independent component that provides configuration container.
hyperf/constants                     v1.1.26     A constants component for hyperf.
hyperf/consul                        v1.1.26     A Consul Client for Hyperf.
hyperf/contract                      v1.1.32     The contracts of Hyperf.
hyperf/crontab                       v2.0.0      A crontab component for Hyperf.
hyperf/database                      v1.1.32     A flexible database library.
hyperf/db-connection                 v1.1.26     A hyperf db connection handler for hyperf/database.
hyperf/devtool                       v1.1.31     A Devtool for Hyperf.
hyperf/di                            v1.1.28     A DI for Hyperf.
hyperf/dispatcher                    v1.1.26     A HTTP Server for Hyperf.
hyperf/event                         v1.1.26     an event manager that implements PSR-14.
hyperf/exception-handler             v1.1.31     Exception handler for hyperf
hyperf/framework                     v1.1.27     A coroutine framework that focuses on hyperspeed and flexible, specifically use for ...
hyperf/guzzle                        v1.1.26     Swoole coroutine handler for guzzle
hyperf/http-message                  v1.1.26     microservice framework base on swoole
hyperf/http-server                   v1.1.29     A HTTP Server for Hyperf.
hyperf/json-rpc                      v1.1.30     A JSON RPC component for Hyperf RPC Server or Client.
hyperf/load-balancer                 v1.1.26     A load balancer library for Hyperf.
hyperf/logger                        v1.1.26     A logger component for hyperf.
hyperf/memory                        v1.1.26     An independent component that use to operate and manage memory.
hyperf/model-cache                   v1.1.28     A model cache component for hyperf.
hyperf/model-listener                v1.1.26     A model listener for Hyperf.
hyperf/paginator                     v1.1.26     A paginator component for hyperf.
hyperf/pool                          v1.1.32     An independent universal connection pool component.
hyperf/process                       v1.1.26     A process component for hyperf.
hyperf/redis                         v1.1.26     A redis component for hyperf.
hyperf/rpc                           v1.1.26     A rpc basic library for Hyperf.
hyperf/rpc-client                    v1.1.28     An abstract rpc server component for Hyperf.
hyperf/rpc-server                    v1.1.26     An abstract rpc server component for Hyperf.
hyperf/server                        v1.1.32     A base server library for Hyperf.
hyperf/service-governance            v1.1.28     A service governance component for Hyperf.
hyperf/testing                       v1.1.28     Testing for hyperf
hyperf/tracer                        v1.1.26     A open tracing system implemented for Hyperf or other coroutine framework
hyperf/utils                         v1.1.31     A tools package that could help developer solved the problem quickly.

**Comment by ArcherZdip** [comment]
> 我这里也是这种情况：
> 
> 96qbhy/hyperf-auth v1.6.1 hyperf 的 auth 组件
> hyperf/amqp v1.1.32 A amqplib for hyperf.
> hyperf/async-queue v1.1.26 A async queue component for hyperf.
> hyperf/cache v1.1.30 A cache component for hyperf.
> hyperf/command v1.1.32 Command for hyperf
> hyperf/config v1.1.26 An independent component that provides configuration container.
> hyperf/constants v1.1.26 A constants component for hyperf.
> hyperf/consul v1.1.26 A Consul Client for Hyperf.
> hyperf/contract v1.1.32 The contracts of Hyperf.
> hyperf/crontab v2.0.0 A crontab component for Hyperf.
> hyperf/database v1.1.32 A flexible database library.
> hyperf/db-connection v1.1.26 A hyperf db connection handler for hyperf/database.
> hyperf/devtool v1.1.31 A Devtool for Hyperf.
> hyperf/di v1.1.28 A DI for Hyperf.
> hyperf/dispatcher v1.1.26 A HTTP Server for Hyperf.
> hyperf/event v1.1.26 an event manager that implements PSR-14.
> hyperf/exception-handler v1.1.31 Exception handler for hyperf
> hyperf/framework v1.1.27 A coroutine framework that focuses on hyperspeed and flexible, specifically use for ...
> hyperf/guzzle v1.1.26 Swoole coroutine handler for guzzle
> hyperf/http-message v1.1.26 microservice framework base on swoole
> hyperf/http-server v1.1.29 A HTTP Server for Hyperf.
> hyperf/json-rpc v1.1.30 A JSON RPC component for Hyperf RPC Server or Client.
> hyperf/load-balancer v1.1.26 A load balancer library for Hyperf.
> hyperf/logger v1.1.26 A logger component for hyperf.
> hyperf/memory v1.1.26 An independent component that use to operate and manage memory.
> hyperf/model-cache v1.1.28 A model cache component for hyperf.
> hyperf/model-listener v1.1.26 A model listener for Hyperf.
> hyperf/paginator v1.1.26 A paginator component for hyperf.
> hyperf/pool v1.1.32 An independent universal connection pool component.
> hyperf/process v1.1.26 A process component for hyperf.
> hyperf/redis v1.1.26 A redis component for hyperf.
> hyperf/rpc v1.1.26 A rpc basic library for Hyperf.
> hyperf/rpc-client v1.1.28 An abstract rpc server component for Hyperf.
> hyperf/rpc-server v1.1.26 An abstract rpc server component for Hyperf.
> hyperf/server v1.1.32 A base server library for Hyperf.
> hyperf/service-governance v1.1.28 A service governance component for Hyperf.
> hyperf/testing v1.1.28 Testing for hyperf
> hyperf/tracer v1.1.26 A open tracing system implemented for Hyperf or other coroutine framework
> hyperf/utils v1.1.31 A tools package that could help developer solved the problem quickly.


执行安装低版本 试试
composer require hyperf/crontab:1.1.26

**Comment by limingxinleo** [comment]
安装1.1版本🉐组件
