### ISSUE TITLE
2.1.0 安装问题

### ISSUE THREAD

**Issue by youmikuang** [hyperf/crontab#4]
Problem 1
    - Conclusion: don't install hyperf/crontab v2.1.0
    - Conclusion: don't install hyperf/crontab v2.1.0-beta1
    - Conclusion: don't install hyperf/crontab 2.1.x-dev
    - Conclusion: remove hyperf/contract v2.0.13
    - Installation request for hyperf/crontab ^2.1 -> satisfiable by hyperf/crontab[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - Conclusion: don't install hyperf/contract v2.0.13
    - hyperf/crontab 2.1.x-dev requires hyperf/utils ~2.1.0 -> satisfiable by hyperf/utils[2.1.x-dev, v2.1.0, v2.1.0-beta1, v2.1.0-beta2, v2.1.0-beta3].
    - hyperf/utils 2.1.x-dev requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - hyperf/utils 2.1.x-dev requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - hyperf/utils v2.1.0 requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - hyperf/utils v2.1.0-beta1 requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - hyperf/utils v2.1.0-beta2 requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - hyperf/utils v2.1.0-beta3 requires hyperf/contract ~2.1.0 -> satisfiable by hyperf/contract[2.1.x-dev, v2.1.0, v2.1.0-beta1].
    - Can only install one of: hyperf/contract[2.1.x-dev, v2.0.13].
    - Can only install one of: hyperf/contract[2.1.x-dev, v2.0.13].
    - Can only install one of: hyperf/contract[v2.1.0, v2.0.13].
    - Can only install one of: hyperf/contract[v2.1.0-beta1, v2.0.13].
    - Installation request for hyperf/contract (locked at v2.0.13) -> satisfiable by hyperf/contract[v2.0.13].

**Comment by limingxinleo** [comment]
请按照更新文档进行升级

**Comment by limingxinleo** [comment]
如果你要安装2.0版本，请带版本号

**Comment by youmikuang** [comment]
好的 谢谢 @limingxinleo
